drop table if exists book;
drop table if exists author;
create table book (
                      id BIGINT GENERATED by default as IDENTITY not null,
                      isbn varchar(255),
                      publisher varchar(255),
                      title varchar(255),
                      primary key (id)
) engine=InnoDB;

create table author (
                        id BIGINT GENERATED by default as IDENTITY not null,
                        first_name varchar(255),
                        last_name varchar(255),
                        primary key (id)
) engine=InnoDB;

